---
name: roboweb-0.1

releases:
- name: roboweb-0.1
  version: latest

networks:
- name: default
  subnets:
  - range: 10.244.0.0/20
    reserved: [10.244.0.1]
    static: [10.244.0.2,10.244.0.6,10.244.0.10]

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default

compilation:
  workers: 1
  network: default

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
- name: app
  templates:
  - name: app
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.244.0.6
  properties: {}

packages:
- name: java
  version: 5af5fcdc6ea141b961148fcda28fc088c0024177
  fingerprint: 5af5fcdc6ea141b961148fcda28fc088c0024177
  sha1: 317686ab17d6ba2e0653560e555b9b5fd86f24cf
  dependencies: []
- name: tomcat
  version: f4ec33af1646ac93b4b0a9f012a4d6aeb45fbc9f
  fingerprint: f4ec33af1646ac93b4b0a9f012a4d6aeb45fbc9f
  sha1: d73d43e9b9825798959cb02be0f78c42f7a8dbed
  dependencies:
  - java
