#!/bin/bash

# $1 = username and password
# $2 = org
# $3 = org role

cf create-user $1 $1
cf set-org-role $1 $2 $3

USERNAME=admin
HOSTNAME=node8
MYSQLSTART='mysql -u root robocode -e "insert into roles (userid,role, org) values('
VALUES="'"$1"','"$3"','"$2"'"
MYSQLEND=');"'
SCRIPT=$MYSQLSTART$VALUES$MYSQLEND 
echo $SCRIPT

ssh -o StrictHostKeyChecking=no -l ${USERNAME} ${HOSTNAME} "${SCRIPT}"
exit

