/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-09-10 20:45:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1505054080000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<script src=\"includes/dropdown.js\"></script>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Welcome Page</title>\n");
      out.write("<!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Custom CSS -->\n");
      out.write("<link href=\"css/freelancer.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Custom Fonts -->\n");
      out.write("<link href=\"font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\"\n");
      out.write("\ttype=\"text/css\">\n");
      out.write("<link\n");
      out.write("\thref='https://fonts.googleapis.com/css?family=Righteous|Fredoka+One'\n");
      out.write("\trel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("<link\n");
      out.write("\thref=\"http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic\"\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<script src=\"http://code.jquery.com/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("\thref=\"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link href=\"css/style_header.css\" rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<script\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("\tsrc=\"http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Custom CSS -->\n");
      out.write("<link href=\"css/freelancer.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Custom Fonts -->\n");
      out.write("<link href=\"font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\"\n");
      out.write("\ttype=\"text/css\">\n");
      out.write("<link\n");
      out.write("\thref='https://fonts.googleapis.com/css?family=Righteous|Fredoka+One'\n");
      out.write("\trel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("<link\n");
      out.write("\thref=\"http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic\"\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<script src=\"http://code.jquery.com/jquery.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body id=\"page-top\" class=\"index\">\n");
      out.write("\t<!-- Navigation -->\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-fixed-top\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("\t\t<div class=\"navbar-header page-scroll\">\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\n");
      out.write("\t\t\t\tdata-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"welcome.jsp\">Robocode</a>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\"\n");
      out.write("\t\t\tid=\"bs-example-navbar-collapse-1\">\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t<li class=\"hidden\"><a href=\"#page-top\"></a></li>\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a href=\"#new\">New</a>\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"NewRobot.jsp\">Robot</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#CUser\">User</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#CDomain\">Domain</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#CRole\">Role</a></li>\n");
      out.write("\t\t\t\t\t</ul></li>\n");
      out.write("\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a href=\"#edit\">Edit</a>\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"Edit_Robot3.jsp\">Robot</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#EUser\">User</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#EDomain\">Domain</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#ERole\">Role</a></li>\n");
      out.write("\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a href=\"#view\">View</a>\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"ViewRobot.jsp\">Robot</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#VUser\">User</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#VDomain\">Domain</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#VRole\">Role</a></li>\n");
      out.write("\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t<li class=\"page-scroll\"><a href=\"PlayBattle.jsp\">Play Battle!</a></li>\n");
      out.write("\t\t\t\t<li class=\"page-scroll\"><a href=\"#view\">Settings</a></li>\n");
      out.write("\t\t\t\t<li class=\"page-scroll\"><a href=\"#view\"><img\n");
      out.write("\t\t\t\t\t\tclass=\"img-responsive\" src=\"img/power button.png\" alt=\"\"\n");
      out.write("\t\t\t\t\t\tALIGN=\"RIGHT\" hspace=\"1\">Logout</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- /.navbar-collapse -->\n");
      out.write("\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\t</body>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("function submit() {\n");
      out.write("\t$(\"#role\").submit();\n");
      out.write("}\n");
      out.write("\n");
      out.write("function submit1() {\n");
      out.write("\t$(\"#heirarchy\").submit();\n");
      out.write("}\n");
      out.write("function submit2() {\n");
      out.write("\t$(\"#heirarchyc\").submit();\n");
      out.write("}\n");
      out.write("function submit3() {\n");
      out.write("\t$(\"#editrole\").submit();\n");
      out.write("}\n");
      out.write("function submit4() {\n");
      out.write("\t$(\"#heirarchyEdit\").submit();\n");
      out.write("}\n");
      out.write("function submit5() {\n");
      out.write("\t$(\"#packageEdit\").submit();\n");
      out.write("}\n");
      out.write("function submit6() {\n");
      out.write("\t$(\"#maph\").submit();\n");
      out.write("}\n");
      out.write("function submit8() {\n");
      out.write("\t$(\"#Ppermissionedit\").submit();\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t<!-- /.container-fluid  </nav>-->\n");
      out.write("\t<!-- Header -->\n");
      out.write("\t<header>\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\n");
      out.write("\t\t\t\t<img class=\"img-responsive\" src=\"includes/robocode_logo_tanks.png\"\n");
      out.write("\t\t\t\t\talt=\"\">\n");
      out.write("\t\t\t\t<div class=\"intro-text\">\n");
      out.write("\t\t\t\t\t<span class=\"name\">Welcome to Robocode!</span>\n");
      out.write("\t\t\t\t\t<hr class=\"star-light\">\n");
      out.write("\t\t\t\t\t<span class=\"skills\">Build the best, destroy the rest!</span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t<!--  <section id=\"portfolio\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-lg-12 text-center\">\n");
      out.write("\t\t\t\t<h2>Example Battle</h2>\n");
      out.write("\t\t\t\t<hr class=\"star-primary\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<iframe width=\"720\" height=\"315\"\n");
      out.write("\t\t\tsrc=\"https://www.youtube.com/embed/8Eo0ueaywcw\" frameborder=\"0\"\n");
      out.write("\t\t\tallowfullscreen></iframe>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t</section>-->\n");
      out.write("\t<footer class=\"text-center\">\n");
      out.write("\t<div class=\"footer-above\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<!--  <div class=\"footer-col col-md-4\">-->\n");
      out.write("\t\t\t\t\t<h3>About Robocode</h3>\n");
      out.write("\t\t\t\t\t<center>\n");
      out.write("\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\tRobocode is a programming game where the goal is to code a robot\n");
      out.write("\t\t\t\t\t\tbattle tank to compete against other robots in a battle arena. So\n");
      out.write("\t\t\t\t\t\tthe name Robocode is a short for \"Robot code\". The player is the\n");
      out.write("\t\t\t\t\t\tprogrammer of the robot, who will have no direct influence on the\n");
      out.write("\t\t\t\t\t\tgame. Instead, the player must write the AI of the robot telling\n");
      out.write("\t\t\t\t\t\tit how to behave and react on events occurring in the battle\n");
      out.write("\t\t\t\t\t\tarena. Battles are running in real-time and on-screen.</a>\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</center>\n");
      out.write("\t\t\t\t<!--  </div> -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"footer-below\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">Copyright &copy; 2016</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\t<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->\n");
      out.write("\t<div class=\"scroll-top page-scroll visible-xs visible-sm\">\n");
      out.write("\t\t<a class=\"btn btn-primary\" href=\"#page-top\"> <i\n");
      out.write("\t\t\tclass=\"fa fa-chevron-up\"></i>\n");
      out.write("\t\t</a>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- jQuery -->\n");
      out.write("\t<script src=\"js/jquery.js\"></script>\n");
      out.write("\n");
      out.write("\t<!-- Bootstrap Core JavaScript -->\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<!-- Plugin JavaScript -->\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js\"></script>\n");
      out.write("\t<script src=\"js/classie.js\"></script>\n");
      out.write("\t<script src=\"js/cbpAnimatedHeader.js\"></script>\n");
      out.write("\n");
      out.write("\t<!-- Custom Theme JavaScript -->\n");
      out.write("\t<script src=\"js/freelancer.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
